### ISSUE TITLE
Insert into query blocks all other queries

### ISSUE THREAD

**Issue by evangelos-dimitriadis** [MonetDB/MonetDB#7184]
**Describe the bug**
An insert into will block any other query executed afterwards. The query will use only 1 core from the CPU.

**To Reproduce**
* Create a database and open mclient two times 
* Create a table as: `CREATE TABLE IF NOT EXISTS alpha (id bigint PRIMARY KEY AUTO_INCREMENT, data bigint); ` 
* In the first mclient execute `INSERT INTO sys.alpha (data) select * from generate_series(0,100000000,cast (1 as bigint));` and **immediately** in the second mclient execute `SELECT 1;`

**Expected behavior**
Another query can be executed in parallel with an insert into query.

**Software versions**
 - MonetDB Jul2021 v11.41.5
 - OS and version: Ubuntu 20.04

**Comment by yzchang** [comment]
Please try this with Jul2021-SP1.  This sounds very similar to something we fixed in Jul2021-SP1

**Comment by aris-koning** [comment]
Indeed doesn't seem to block on default

**Comment by sstalin** [comment]
I was able to reproduce it on default

**Comment by aris-koning** [comment]
Interestingly I actually cannot reproduce it on a Jul2021 original build either. Not with a debug or release build.

**Comment by evangelos-dimitriadis** [comment]
MonetDB v11.41.11 (Jul2021-SP1) has still the same problem for me.

**Comment by aris-koning** [comment]
Got it now. Was my fault. I didn't exactly used the above query. The primary index seems to be an essential constituent for the reproduction of this problem.

**Comment by yzchang** [comment]
The blocking `SELECT 1` Sjoerd and I have worked on was not caused by an INSERT INTO, so it's possible there are still some overlooked blocking factors.

@evangelos-dimitriadis Can you upload a full GDB stack trace from a moment when your SELECT 1 is blocked?  I.e., output of the GDB command `thread apply all bt full`

**Comment by aris-koning** [comment]
I think the problem is in mvc_bat_next_get_value. It uses a custom batloop to insert values in a bat. Which is locking and unlocking all kinds of locks quite a lot. and it seems to block entire clients

**Comment by aris-koning** [comment]
`mvc_bat_next_get_value` acquires a long lasting lock on the store which blocks the creation of new transactions and therefore the progress of new clients. I have to talk with @njnes to see what we can do about this.

**Comment by njnes** [comment]
fixes went into the default branch (ie the merge of the sequence_7184 branch).
